### ISSUE TITLE
Explore OpenSUSE build service possibilities

### ISSUE THREAD

**Issue by Polpetta** [Polpetta/jkk#12]
It would be cool to have a place that builds and distributes RPM, DEB and ArchLinux packages in only one place.

I've see that OBS Open build service does something like that (https://build.opensuse.org/) but I'm not sure about it, since I've never had the possibility to use it.
It would be cool to adopt something like that, so every time a new release comes out, packages are already distributed in distro-specific repositories.

**Comment by M0Rf30** [comment]
I'm working on it ;). The main problem for now is gradle make dep, cause it's not available in its latest versions, also on latest deb based distros. versions under 4.9 of gradle are not compatibile with kotlin plugin. Look at pacur branch for a working workaround. repology and pkgs.org are true mates to accomplish this job

**Comment by Polpetta** [comment]
Cool! On top of that, I noticed the current project configuration is not valid for Gradle 7.0...as soon as I have time I'll dig in that, so for bleeding-edge distros (e.g. Arch :wink: ) we won't have any surprise when Gradle 7.0 comes in town (atm in Arch stable the distributed version is the 6.0.1 one...)

**Comment by M0Rf30** [comment]
at commit 98ec8cee71cf29e31e3add38289cc9c25e0f2f8e I fixed the deprecation for gradle 7.0 ;)

**Comment by Polpetta** [comment]
Always on top, great job :+1:!

**Comment by M0Rf30** [comment]
Yes. I know I've swapped the requests. I added opensuse support with pacur, instead of exploring OBS features :DDD.

**Comment by Polpetta** [comment]
Hahah no problem man :joy: We're here for having fun and chill

**Comment by M0Rf30** [comment]
OBS, AFAIK, is so slow and not intuitive also if you start to dive in the official docs. I would like to suggest the use of bintray open source account. I'm just having a tour within it and it seems very well designed. After pacur pipeline the ideal will be sign and upload the packages on a package optimized hosting service and bintray seems to fit this task

**Comment by M0Rf30** [comment]
Can we close this cause of pacur choice?

**Comment by Polpetta** [comment]
Yep!
