### ISSUE TITLE
Install directive in build.gradle don't exclude jar task, doubling the size of generated artifacts

### ISSUE THREAD

**Issue by M0Rf30** [Polpetta/jkk#25]
There should be a flag to exclude **jar** task from **install** one. Now it generates all the required resources to distribute the software but doubles the size of the assets required for packaging, cause the jkk.jar contains the .class generated by **jar** task also provided by **install**

**Comment by Polpetta** [comment]
Related Gradle documentation: https://docs.gradle.org/current/dsl/org.gradle.api.Task.html

**Comment by Polpetta** [comment]
Additional: https://docs.gradle.org/current/userguide/building_java_projects.html
