### ISSUE TITLE
Consider changing Jenkins Client

### ISSUE THREAD

**Issue by apontini** [Polpetta/jkk#3]
I was trying to implement a "list" command to list every job created in jenkins but there is no "list job API" within our Java jenkins client, which seems odd to me.
Any reasons on why [cdancy jenkins client](https://github.com/cdancy/jenkins-rest) was picked instead of [jenkinsci client](https://github.com/jenkinsci/java-client-api)?
The latter is still an active project and imho it's WAY better documented (at least within its javadoc)

**Comment by Polpetta** [comment]
Yep, I noticed it as well. Honestly when I started I followed the link inside our Jenkins instance, without even checking for other libraries... I think we should switch library before its too late!

On top of that, maybe it would be cool to make an Adapter in case we need to switch again?

**Comment by apontini** [comment]
It might be worth the effort now that the project is in it's very early stages so that we can keep updating it with new features as the project grows
